FROM node:12

WORKDIR /app
ADD frontend/package.json /app/package.json
RUN npm install
# RUN npm install react-scripts

ADD wait_for_it.sh /opt/wait_for_it.sh
RUN chmod +x /opt/wait_for_it.sh
EXPOSE 3000

COPY ./frontend /app
